matrix:
- name: asciidoc source py spell check configuration
  aspell:
    lang: en
    d: en_US
  sources:
  - documentation/*.asciidoc 
  dictionary:
    wordlists:
    - en-devonfw.dict
    output:  en-devonfw.dic
  pipeline:
  - pyspelling.filters.url:
  #Ignore for directory path
  - pyspelling.filters.context: 
      context_visible_first: true
      escapes: '^.*[\/\\][^\/\\]+$'
<<<<<<< HEAD
  #Ignore for url starting with http or https
  - pyspelling.filters.context: 
      context_visible_first: true
      delimiters:
      - open: 'https?:\S+?'
        close: '\s'
  #Ignore content between backticks
  - pyspelling.filters.context: 
      context_visible_first: true
      delimiters:
      - open: '```'
        close: '(\w|\W)+?(?=```)'
=======
>>>>>>> fbcd15c62d3cc027fdcb6cfca7268c708eae9032
  #Ignore content between backticks
  - pyspelling.filters.context: 
      context_visible_first: true
      delimiters:
<<<<<<< HEAD
      - open: '(?<!``)`[^`]+'
        close: '`'
  #Ignore links
  - pyspelling.filters.context: 
      context_visible_first: true
      delimiters:
      - open: 'link:[^[]+'
        close: '\['
  #Ignore Image tags
  - pyspelling.filters.context: 
      context_visible_first: true
      delimiters:
      - open: 'image:[^[]+'
        close: '\['
  #Ignore Image tags link part
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: ',.+?link=[^\]]+'
        close: '\]'
  #Ignore include tag
  - pyspelling.filters.context: 
      context_visible_first: true
      delimiters:
      - open: 'include:[^[]+'
        close: '\['
=======
      - open: '`+[^`]+'
        close: '`+'
  #Ignore for upper camel case
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: '\b[A-Z][a-z0-9]+[A-Z]'
        close: '[a-z0-9]*\b'
  #Ignore for lower camel case
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: '\b[a-z]+[A-Z]'
        close: '[a-z0-9]*\b'
  #Ignore for constants in upper case
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: '\b[A-Z]+'
        close: '([_][A-Z]+)*\b'
  #Ignore for special cases in CobiGen in upper camel case
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: '\b__[A-Z][a-z0-9]+[A-Z]'
        close: '[a-z0-9.]*__\b'
>>>>>>> fbcd15c62d3cc027fdcb6cfca7268c708eae9032
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: \\[\\-~]
      delimiters:
      # Ignore multiline content between fences (fences can have 4 or more hyphens)
      # ----
      # content
      # ----
      - open: '(?s)^(?P<open> *-{4,})$'
        close: '^(?P=open)$'  
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      # Ignore multiline content between [source, *] and blank line
<<<<<<< HEAD
      - open: '\[source, .*\]\r?\n\s*----'
        close: '[^-]*'
=======
      - open: '\[source,.*\]'
        close: '^\s*$'   
>>>>>>> fbcd15c62d3cc027fdcb6cfca7268c708eae9032
