matrix:
- name: asciidoc source py spell check configuration
  aspell:
    lang: en
    d: en_US
  sources:
  - documentation/*.asciidoc 
  dictionary:
    wordlists:
    - en-devonfw.dict
    output:  en-devonfw.dic
  pipeline:
  - pyspelling.filters.url:
  #Ignore for directory path
  - pyspelling.filters.context: 
      context_visible_first: true
      escapes: '^.*[\/\\][^\/\\]+$'
  #Ignore content between backticks
  - pyspelling.filters.context: 
      context_visible_first: true
      delimiters:
      - open: '`+[^`]+'
        close: '`+'
  #Ignore for upper camel case
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: '\b[A-Z][a-z0-9]+[A-Z]'
        close: '[a-z0-9]*\b'
  #Ignore for lower camel case
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: '\b[a-z]+[A-Z]'
        close: '[a-z0-9]*\b'
  #Ignore for constants in upper case
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: '\b[A-Z]+'
        close: '([_][A-Z]+)*\b'
  #Ignore for special cases in CobiGen in upper camel case
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: '\b__[A-Z][a-z0-9]+[A-Z]'
        close: '[a-z0-9.]*__\b'
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: \\[\\-~]
      delimiters:
      # Ignore multiline content between fences (fences can have 4 or more hyphens)
      # ----
      # content
      # ----
      - open: '(?s)^(?P<open> *-{4,})$'
        close: '^(?P=open)$'  
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      # Ignore multiline content between [source, *] and blank line
      - open: '\[source,.*\]'
        close: '^\s*$'   
