matrix:
- name: asciidoc source py spell check configuration
  aspell:
    lang: en
    d: en_US
  sources:
  - documentation/*.asciidoc 
  dictionary:
    wordlists:
    - en-devonfw.dict
    output:  en-devonfw.dic
  pipeline:
  - pyspelling.filters.url:
  #Ignore for directory path
  - pyspelling.filters.context: 
      context_visible_first: true
      escapes: '^.*[\/\\][^\/\\]+$'
  #Ignore content between backticks
  - pyspelling.filters.context: 
      context_visible_first: true
      delimiters:
      - open: '`+[^`]+'
        close: '\['
  #Ignore links
  - pyspelling.filters.context: 
      context_visible_first: true
      escapes: 'link:[^[]+\['
  #Ignore Image tags
  - pyspelling.filters.context: 
      context_visible_first: true
      escapes: 'image::[^[]+\['
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      # Ignore Image tag content after name
      - open: '(?:(?<=image::[^[]+\[[^,]+),[^\]]+)'
        close: '\]'
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: \\[\\-~]
      delimiters:
      # Ignore multiline content between fences (fences can have 4 or more hyphens)
      # ----
      # content
      # ----
      - open: '(?s)^(?P<open> *-{4,})$'
        close: '^(?P=open)$'  
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      # Ignore multiline content between [source, *] and blank line
      - open: '\[source, .*\]'
        close: '^\s*$'
