{
  "name": "oasp-js-sample",
  "description": "Sample application making use of The JavaScript Open Application Standard Platform",
  "author": "The OASP Team",
  "version": "0.0.1",
  "dependencies": {
    "connect": "3.3.3"
  },
  "devDependencies": {
    "browser-sync": "~1.8.1",
    "chalk": "~0.5.1",
    "coveralls": "^2.11.2",
    "del": "^1.1.1",
    "gulp": "~3.9.0",
    "gulp-concat": "^2.4.2",
    "gulp-filter": "~1.0.2",
    "gulp-flatten": "~0.0.4",
    "gulp-git": "^0.5.6",
    "gulp-if": "^1.2.5",
    "gulp-imagemin": "~2.0.0",
    "gulp-inject": "~1.0.2",
    "gulp-insert": "0.4.0",
    "gulp-jshint": "~1.9.0",
    "gulp-karma": "~0.0.4",
    "gulp-less": "~1.3.6",
    "gulp-load-plugins": "~0.7.1",
    "gulp-minify-css": "^0.3.11",
    "gulp-minify-html": "~0.1.7",
    "gulp-newer": "^0.5.0",
    "gulp-ng-annotate": "~0.5.2",
    "gulp-ng-templates": "0.0.5",
    "gulp-processhtml": "^1.0.2",
    "gulp-protractor": "~0.0.11",
    "gulp-replace": "~0.5.0",
    "gulp-rev": "~2.0.1",
    "gulp-size": "~1.1.0",
    "gulp-sonar": "^1.0.3",
    "gulp-sourcemaps": "^1.2.8",
    "gulp-sync": "^0.1.4",
    "gulp-uglify": "~1.0.1",
    "gulp-usemin": "^0.3.8",
    "gulp-util": "^3.0.1",
    "gulp.spritesmith": "^2.4.0",
    "http-proxy": "~1.7.0",
    "jshint-stylish": "~1.0.0",
    "karma-chrome-launcher": "^0.1.4",
    "karma-coverage": "0.2.6",
    "karma-jasmine": "~0.3.1",
    "karma-junit-reporter": "~0.2.2",
    "karma-phantomjs-launcher": "~0.1.4",
    "lodash": "^3.0.0",
    "main-bower-files": "~2.4.0",
    "protractor": "~1.4.0",
    "require-dir": "~0.1.0",
    "string": "^3.0.0",
    "through2": "~0.4.1",
    "uglify-save-license": "~0.4.1",
    "wiredep": "~2.2.0",
    "yargs": "^1.3.3"
  },
  "engine": "node >= 0.10.0",
  "scripts": {
    "postinstall": "bower install -F",
    "test": "gulp test"
  }
}
