/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by CobiGen.
 */
<#include "model.ts.ftl">

export interface ${variables.etoName?cap_first} {
<#compress>
<#list model.properties as property>
    ${property.name}?: ${OpenApiUtil.toTypeScriptType(property)};
</#list>
</#compress>

}
