/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by CobiGen.
 */
<#compress>
<#list model.properties as property>
    <#if property.isEntity> import { ${property.type} } from './${property.type}'; </#if>
</#list>
</#compress>

export interface ${variables.etoName?cap_first} {
<#compress>
<#list model.properties as property>
    ${property.name}?: ${property.type};
</#list>
</#compress>

}
