language: node_js
branches:
  only:
    - development
node_js:
  - "0.10"
before_install:
  - npm install -g bower
  - npm install -g gulp
after_success:
  - cat ./test/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
