name: spellcheck 
on:
  push:
  workflow_dispatch:
jobs:
  spellchecker:
    uses: devonfw/.github/.github/workflows/devonfw-spellchecker.yml@master
    secrets:
      RESUSABLE_GH_ACTION_TOKEN: ${{ secrets.RESUSABLE_GH_ACTION_TOKEN }}
